apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: kserve-ovms
spec:
  multiModel: false
  annotations:
    prometheus.kserve.io/port: '8888'
    prometheus.kserve.io/path: /metrics
  supportedModelFormats:
    - name: openvino_ir
      version: opset13
      autoSelect: true
    - name: onnx
      version: '1'
    - name: tensorflow
      version: '1'
      autoSelect: true
    - name: tensorflow
      version: '2'
      autoSelect: true
    - name: paddle
      version: '2'
      autoSelect: true
    - name: pytorch
      version: '2'
      autoSelect: true
  protocolVersions:
    - v2
    - grpc-v2
  containers:
    - name: kserve-container
      image: quay.io/modh/openvino_model_server:rhoai-2.8-final
      args:
        - '--model_name=mnist'
        - '--port=8001'
        - '--rest_port=8888'
        - '--model_path=/mnt/models'
        - '--file_system_poll_wait_seconds=0'
        - '--grpc_bind_address=127.0.0.1'
        - '--rest_bind_address=127.0.0.1'
        - '--target_device=AUTO'
        - '--metrics_enable'
      ports:
        - containerPort: 8888
          protocol: TCP
